name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Version of buildpacks/github-actions
        run: |
            sed -i 's/4.2.0/4.3.0/g' .github/workflows/register-buildpack.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.DISTRIBUTION_GITHUB_TOKEN }}
          commit-message: update version to 4.3.0
          title: Update Version of buildpacks/github-actions
          body: Update version to reflect release changes
          branch: update-version
          base: main
